[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/audio-manager/*"
  to = "/audio-manager.html"
  status = 200

[[redirects]]
  from = "/audio-manager"
  to = "/audio-manager.html"
  status = 200

# Handle SPA routing for the main app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for audio files
[[headers]]
  for = "/audio/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "audio/mpeg"

# Headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
